# Generated by Django 4.0.2 on 2022-04-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NagraDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.CharField(blank=True, max_length=30)),
                ('network_name', models.CharField(blank=True, max_length=30)),
                ('bouquet_id', models.CharField(blank=True, max_length=30)),
                ('bouquet_name', models.CharField(blank=True, max_length=30)),
                ('transport_id', models.CharField(blank=True, max_length=30)),
                ('channel_name', models.CharField(blank=True, max_length=30)),
                ('call_sign', models.CharField(blank=True, max_length=30)),
                ('products', models.CharField(blank=True, max_length=30)),
                ('frequency', models.CharField(blank=True, max_length=30)),
                ('modulation', models.CharField(blank=True, max_length=30)),
                ('transport_key', models.CharField(blank=True, max_length=30)),
                ('service_key', models.CharField(blank=True, max_length=30)),
                ('channel_number', models.CharField(blank=True, max_length=30)),
                ('alternate_channel_number', models.CharField(blank=True, max_length=30)),
                ('dvbsi_mpeg', models.CharField(blank=True, max_length=30)),
                ('acref_int', models.CharField(blank=True, max_length=30)),
                ('acref_hex', models.CharField(blank=True, max_length=30)),
                ('original_network_id', models.CharField(blank=True, max_length=30)),
                ('scrambling_algorithm', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
